server:
  servlet:
    context-path: /api
    session:
      timeout: PT60M
# 异常处理
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/easypan?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd hh:mm:ss
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  # 发送邮件配置相关
  mail:
    port: 587   # 配置邮件服务器的端口（465或587
    host: smtp.qq.com   # 配置邮件服务器的地址 smtp.qq.com
    username: 2740860037@qq.com   # 配置用户的账号
    password: aczotlkbphomdchd   # 配置用户的密码
    default-encoding: UTF-8    # 配置默认编码
    properties: # SSL 连接配置
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true    # 开启 debug，这样方便开发者查看邮件发送日志
  # Spring redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 2000    # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 20   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
## 日志目录
project:
  folder: E:/大学自学/程序员老罗/云盘
## 日志级别配置
#log:
#  root:
#    level: debug
# qq登陆相关
qq:
  app:
    id: 102055758
    key: Y0EITXS4XBey4xc2
  url:
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    redirect: https://hechao.online/qq/qqlogin/callback
    access:
      token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    user:
      info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
#超级管理员id
admin:
  emails: 2740860037@qq.com




